### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ORTIGAgames** [ORTIGAgames/OrtigaGames#17]
El tutorial posee varios fallos que deben ser arreglados:

## To Do

- [x] El juego crashea al completar el tutorial
- [x] no explica debidamente lo que debería hacer el jugador para completarlo
- [x] Arreglar cuadro de diálogo para que no tape otros botones
- [x] El menú de mejoras no deja pasar el diálogo
- [x] Se tarda mucho en matar al enemigo del tutorial
- [x] Arreglar el botón de pausa en el tutorial ya que los botones se quedan bloqueados

**Comment by Yibus13** [comment]
Tutorial arreglado, ahora solo queda saber si la gente le gusta o no
